version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=SOCIAL_NETWORK
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mysql_data:
