// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RabbitMQClient is an autogenerated mock type for the RabbitMQClient type
type RabbitMQClient struct {
	mock.Mock
}

// Connect provides a mock function with given fields:
func (_m *RabbitMQClient) Connect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consume provides a mock function with given fields: queueName
func (_m *RabbitMQClient) Consume(queueName string) (<-chan []byte, error) {
	ret := _m.Called(queueName)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 <-chan []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (<-chan []byte, error)); ok {
		return rf(queueName)
	}
	if rf, ok := ret.Get(0).(func(string) <-chan []byte); ok {
		r0 = rf(queueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(queueName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Disconnect provides a mock function with given fields:
func (_m *RabbitMQClient) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: queueName, message
func (_m *RabbitMQClient) Publish(queueName string, message []byte) error {
	ret := _m.Called(queueName, message)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(queueName, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRabbitMQClient creates a new instance of RabbitMQClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRabbitMQClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RabbitMQClient {
	mock := &RabbitMQClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
